services:
  app:
    image: blogs-ui-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    # SKip volume mapping due to ARM64 issues
    #volumes:
    #  - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: blogs-ui-dev
  debug-helper:
    image: busybox