services:
  mongo:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: mongo
  redis:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: redis
  backend:
    extends:
      file: ./todo-backend/docker-compose.yml
      service: app
    depends_on:
      - mongo
      - redis
  frontend:
    extends:
      file: ./todo-frontend/docker-compose.yml
      service: app
    depends_on:
      - backend
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    container_name: reverse-proxy
    depends_on:
      - frontend
  debug-helper:
    image: busybox          