services:
  app:
    image: blogs-bff-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    container_name: blogs-bff-prod
  debug-helper:
    image: busybox
    