services:
  app:
    image: blogs-bff-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    container_name: blogs-bff-prod
    environment:
      - MONGODB_URI=mongodb+srv://pipeline-user:FfEB0Xp2jcqXy7tJ@cluster0.tszt1iq.mongodb.net/bloglist?appName=Cluster0
      - TEST_MONGODB_URI=mongodb+srv://pipeline-user:FfEB0Xp2jcqXy7tJ@cluster0.tszt1iq.mongodb.net/bloglist_test?appName=Cluster0
      - PORT=3003
      - SECRET=supersecretkey=value
  debug-helper:
    image: busybox
    