services:
  app:
    image: blogs-bff-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3003:3003
    container_name: blogs-bff-dev
  debug-helper:
    image: busybox
    
